package types

import (
	"testing"

	"github.com/ethereum/go-ethereum/common"
)

// TestFoldMMR_IndependentReferenceVectors locks the shared MMR fold (used by
// both FoldInteractionRoot and FoldTypedOpRoot) against the INDEPENDENT
// reference vectors generated by golden/mmr/mmr_reference.py. That reference is
// validated separately against the locked v1_3step production root
// (0xd54c...), and this test cross-checks the Go fold against it over synthetic
// leaves — including the multi-peak boundaries (3=2+1, 5=4+1, 7=4+2+1) and 2^k
// edges that a round-trip fold(txs)==header check cannot catch, and that
// TypedOpRoot previously had no external reference for.
func TestFoldMMR_IndependentReferenceVectors(t *testing.T) {
	// leaf i = 32 bytes all equal to (i+1); trivially reproducible in any lang.
	mk := func(n int) [][32]byte {
		ls := make([][32]byte, n)
		for i := 0; i < n; i++ {
			var l [32]byte
			for k := range l {
				l[k] = byte(i + 1)
			}
			ls[i] = l
		}
		return ls
	}
	cases := map[int]string{
		0:  "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470", // keccak256("")
		1:  "0x0101010101010101010101010101010101010101010101010101010101010101",
		2:  "0x346d8c96a2454213fcc0daff3c96ad0398148181b9fa6488f7ae2c0af5b20aa0",
		3:  "0xf8f23a80fd4d99d9d231122e1f115145412be3856b23abcc338903e32a80c4ef",
		4:  "0x99976d3b1539e7cfaca77649ac7536fec61db00fb0835634915b4d542fff06ae",
		5:  "0x644baaabdf96074e4c3774fcd82cc717cd4d53c48da8ac1e3029ebe434c64996",
		7:  "0x0bb0fa02595e3b7aa3bf12025293c90a73289d7b47a5a74be84ed5a18b84d67c",
		8:  "0x34b356a3cd4d466b202934fb28238054eb6eea84934d361132ad73b0cb2003a9",
		16: "0x49c8ea735d481821b96ab8a8976b5caf4d1f895eeec2f88dbbfd418c88005716",
	}
	for n, want := range cases {
		got := foldMMR(mk(n))
		if got != common.HexToHash(want) {
			t.Fatalf("foldMMR(n=%d): Go fold %s != independent reference %s", n, got.Hex(), want)
		}
	}
}
